swagger: '2.0'
info:
  description: >-
    This is the api definition that every runtime for OpenBrisk must implement to be useful. 
    You can find out more about OpenBrisk at [http://openbrisk.org](http://openbrisk.org).
  version: 1.0.0
  title: OpenBrisk Runtime Specification
  contact:
    email: info@openbrisk.org
  license:
    name: MIT
  basePath: /
  schemes:
    - http
  paths:
    '/':
      get:
        summary: Invoke the function without parameters.
        produces:
          - plain/text
          - application/json
        responses:
          '200':
            description: OK
            headers:
              X-OpenBrisk-Forward:
                description: Forward (POST) the function result to another endpoint.
                schema:
                  type: string
              X-OpenBrisk-Duration:
                  description: The duration of the function execution in nanoseconds.
                  schema:
                      type: int                   
            examples:
              plain/text: Hallo Welt!
              application/json: |-
                {
                  "value": 500,
                  "message": "Hallo Welt!"
                }
          '400':
            description: Bad Request
          '408':
            description: Request Timeout
          '500':
            description: Internal Function Error
      post:
        summary: Invoke the function with parameters.
        consumes:
          - plain/text
          - application/json
        produces:
          - plain/text
          - application/json
        responses:
          '200':
            description: OK
            headers:
              X-OpenBrisk-Forward:
                description: Forward (POST) the function result to another endpoint.
                schema:
                  type: string     
              X-OpenBrisk-Duration:
                  description: The duration of the function execution in nanoseconds.
                  schema:
                      type: int     
            examples:
              plain/text: Hallo Welt!
              application/json: |-
                {
                  "value": 500,
                  "message": "Hallo Welt!"
                }
          '400':
            description: Bad Request
          '408':
            description: Request Timeout            
          '500':
            description: Internal Function Error
    '/healthz':
      get:
        summary: The health check.
      responses:
        '200':
          description: OK
externalDocs:
  description: OpenBrisk runtime documentation available on GitHub.
  url: https://github.com/openbrisk/brisk-runtime